osulp/kiosks

Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20161206233528_devise_create_users.rb, db/schema.rb, spec/models/user_spec.rb
=> added devise gem and generated user model

app/assets/javascripts/react/actions/index.js, app/assets/javascripts/react/actions/modalActions.js, app/assets/javascripts/react/components/ModalWindow.js, app/assets/javascripts/react/components/presentational/shared/ModalWindow.js, app/assets/javascripts/react/reducers/index.js, app/assets/javascripts/react/reducers/modalReducer.js, app/assets/stylesheets/layouts/_main.scss, spec/javascripts/components/__snapshots__/error.test.js.snap, spec/javascripts/components/__snapshots__/slideGallery.test.js.snap, spec/javascripts/components/__snapshots__/touchButtonList.test.js.snap, spec/javascripts/components/presentational/shared/__snapshots__/modalWindow.test.js.snap, spec/javascripts/components/presentational/shared/modalWindow.test.js
=> add basic modal window component with related actions and reducer

app/assets/javascripts/react/components/presentational/shared/ModalWindow.js, app/assets/stylesheets/layouts/_main.scss, spec/javascripts/components/presentational/shared/__snapshots__/modalWindow.test.js.snap, spec/javascripts/components/presentational/shared/modalWindow.test.js
=> add modal window close button and related functionality

Gemfile, Gemfile.lock, app/controllers/api/v1/api_controller.rb, app/controllers/api/v1/concerns/error_handler.rb, app/controllers/api/v1/concerns/version_expiration_handler.rb, app/controllers/api/v1/hours_controller.rb, app/models/api/v1/drupal_hour.rb, app/models/api/v1/drupal_record.rb, circle.yml, config/application_config.example.yml.erb, config/database.yml, config/initializers/api.rb, config/initializers/db_config.rb, config/locales/en.yml, config/routes.rb, lib/api/v1/constraints.rb, lib/api/v1/exceptions.rb, lib/tasks/api/v1/test_drupal_database.rake, spec/controllers/api/v1/concerns/version_expiration_handler_spec.rb, spec/controllers/api/v1/hours_controller_spec.rb, spec/fixtures/api/v1/drupal_schema.rb, spec/spec_helper.rb
=> add foundational ApiController, Drupal hours controller, and related test

README.md, app/assets/javascripts/react/actions/touchActions.js, app/assets/javascripts/react/components/TouchHours.js, app/assets/javascripts/react/components/presentational/Touch/Header.js, app/assets/javascripts/react/components/presentational/Touch/Hours.js, app/assets/javascripts/react/components/presentational/Touch/HoursError.js, app/assets/javascripts/react/components/presentational/Touch/HoursTable.js, app/assets/javascripts/react/components/presentational/Touch/Kiosk.js, app/assets/javascripts/react/reducers/kioskReducer.js, app/assets/javascripts/react/reducers/touchReducer.js, app/assets/stylesheets/layouts/_main.scss, app/assets/stylesheets/layouts/_touch-kiosk.scss, lib/tasks/api/v1/test_drupal_database.rake, package.json, spec/fixtures/api/v1/drupal_schema.rb, spec/javascripts/react/components/__snapshots__/error.test.js.snap, spec/javascripts/react/components/__snapshots__/slideGallery.test.js.snap, spec/javascripts/react/components/presentational/Touch/kiosk.test.js, yarn.lock
=> Touch kiosk hours ui

app/assets/javascripts/react/actions/touchActions.js, app/assets/javascripts/react/components/presentational/Touch/Hours.js, app/assets/javascripts/react/components/presentational/Touch/HoursTable.js, app/assets/stylesheets/layouts/_main.scss, app/assets/stylesheets/layouts/_touch-kiosk.scss, app/models/api/v1/drupal_hour.rb, app/views/kiosk/show.html.erb, config/application_config.example.yml.erb
=> completes the Hours component, UI, and functionality

app/assets/javascripts/react/components/presentational/Touch/Hours.js, app/assets/stylesheets/layouts/_touch-kiosk.scss
=> Touch hours mobile

app/assets/javascripts/react/actions/kioskActions.js, app/assets/javascripts/react/components/DonorKiosk.js, app/assets/javascripts/react/components/presentational/Donor/Kiosk.js, app/assets/javascripts/react/components/presentational/Donor/LargeSlide.js, app/assets/javascripts/react/components/presentational/Donor/SlideCell.js, app/assets/javascripts/react/components/presentational/Donor/SlideGrid.js, app/assets/javascripts/react/reducers/kioskReducer.js, app/assets/stylesheets/layouts/_donor-kiosk.scss, app/views/kiosk/show.json.jbuilder, spec/javascripts/react/.factories.js, spec/javascripts/react/actions/__snapshots__/kioskActions.test.js.snap, spec/javascripts/react/actions/kioskActions.test.js, spec/javascripts/react/components/DonorKiosk.test.js, spec/javascripts/react/components/__snapshots__/DonorKiosk.test.js.snap, spec/javascripts/react/components/__snapshots__/error.test.js.snap, spec/javascripts/react/components/presentational/Donor/Kiosk.test.js, spec/javascripts/react/components/presentational/Donor/LargeSlide.test.js, spec/javascripts/react/components/presentational/Donor/SlideCell.test.js, spec/javascripts/react/components/presentational/Donor/SlideGrid.test.js, spec/javascripts/react/reducers/__snapshots__/kioskReducer.test.js.snap, spec/javascripts/react/reducers/kioskReducer.test.js
Fixes #24 
This adds the base for the donor kiosk. We need to make sure to do some testing with several of the images from the donor kiosk, but after that testing, I think this should be pretty good to go (minus the background made by the student and some other possible styling changes.)
=> adds modal functionality for large slide

app/assets/javascripts/react/components/presentational/Donor/LargeSlide.js, app/assets/stylesheets/layouts/_donor-kiosk.scss
Adds modal CSS animations for modals. Grows from center, then disappears in center.
=> Adds entering and exiting animation for modal popup

app/assets/javascripts/react/components/presentational/Touch/Hours.js, app/assets/stylesheets/layouts/_touch-kiosk.scss
prevents the hours component from hanging out visible forever
=> hides the hours after a timeout when no dates have been selected

package.json, webpack.config.production.js
minifies and compresses code for production
=> setup production webpack

app/assets/javascripts/react/components/presentational/Donor/LargeSlide.js, app/assets/javascripts/react/components/presentational/Donor/SlideCell.js, app/assets/stylesheets/layouts/_donor-kiosk.scss, app/models/slide.rb, spec/javascripts/react/components/presentational/Donor/LargeSlide.test.js
This makes the modal have a darker alpha as well as reformats the small cells and centers the modal large slide.
=> Fixes slide cell size and best fits pictures.

app/assets/javascripts/react/components/presentational/Touch/Header.js
bugfix for image location hosted on server
=> changes image url

app/assets/javascripts/react/components/presentational/Touch/Header.js, app/assets/stylesheets/layouts/_touch-kiosk.scss
navbar will float at the top with the default black background for unfilled space left by a slide in the incorrect aspect ratio. Plus, add the tap feature.
=> align slide to bottom when images don't fit the ideal aspect ratio

app/assets/javascripts/react/components/TouchKiosk.js, app/assets/javascripts/react/components/presentational/Touch/Header.js, app/assets/javascripts/react/components/presentational/Touch/Kiosk.js, app/assets/stylesheets/layouts/_touch-kiosk.scss, spec/javascripts/react/components/presentational/Touch/Header.test.js, spec/javascripts/react/components/presentational/Touch/Kiosk.test.js
updates touch kiosk to auto-refresh slides every hour, and to auto-refresh (and display) "todays hours" every 10 minutes.
=> add todays hours to the touch kiosk header

config/database.yml
bugfix for available room count
=> update database.yml for roomres connection

app/models/api/v1/drupal_hour.rb, app/models/api/v1/drupal_intersession_hour.rb, app/models/api/v1/drupal_special_hour.rb, lib/api/v1/custom_hours_format.rb, spec/lib/api/v1/custom_hours_format_spec.rb
=> added custom hours format module for new formatted_hours field

app/assets/javascripts/react/actions/circActions.js, app/assets/javascripts/react/components/presentational/Circulation/Kiosk.js, app/assets/javascripts/react/components/presentational/Circulation/Rooms.js, app/assets/javascripts/react/components/presentational/Touch/Hours.js, app/assets/javascripts/react/components/presentational/Touch/Kiosk.js, app/controllers/api/v1/rooms_controller.rb, app/views/collections/index.html.erb
- updated rooms controller to get the correct time zone before querying the database for available rooms
- updated kiosks (touch and circulation) to print the correct formats when getting the hours from the database
=> fixed timezone conflicts in touch and circulation kiosks

.gitignore, app/models/api/v1/room_res_room.rb
- moved uploads to a symlink to prevent images uploaded with carrierwave to get lost on deploy
- updated the model api room_res_room to exclude room 2525 for available rooms since it's not available for reservations
=> updated gitignore and room res room model

app/assets/javascripts/application.js, app/assets/javascripts/dragscroll.js, app/assets/javascripts/dragscroll/LICENSE, app/assets/javascripts/dragscroll/README.md, app/assets/javascripts/dragscroll/bower.json, app/assets/javascripts/dragscroll/dragscroll.js, app/assets/javascripts/dragscroll/package.json, app/assets/javascripts/react/components/presentational/Donor/SlideGrid.js, app/assets/stylesheets/layouts/_main.scss
=> fixed donor scroll issue and updated circ style

app/uploaders/image_uploader.rb
=> updated store_dir in image_uploader

app/assets/javascripts/react/components/presentational/Circulation/Kiosk.js, app/assets/javascripts/react/components/presentational/Touch/Kiosk.js
=> bugfix for interval refreshing slides and hours

app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js, app/assets/stylesheets/layouts/_touch-kiosk.scss
=> updated primo iframe style

Gemfile, Gemfile.lock
paperclip was replaced with carrierwave in https://github.com/osulp/kiosks/pull/122
fixes #166
=> removed paperclip gem

app/assets/javascripts/react/components/presentational/Touch/ClassroomSchedule.js, app/assets/javascripts/react/components/presentational/Touch/Hours.js
=> added default_calendar_value state for touch kiosk

Gemfile, Gemfile.lock, app/assets/javascripts/react/components/presentational/Touch/ClassroomSchedule.js, app/assets/javascripts/react/components/presentational/Touch/Header.js, app/assets/javascripts/react/components/presentational/Touch/Hours.js, app/assets/javascripts/react/components/presentational/Touch/Kiosk.js, app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js
aims to fix the bug when tapping the hours button and the default remains as the day the kiosk was restarted
=> adds rubocop for dev env, fix GA console errors

.gitignore, app/assets/javascripts/react/actions/kioskActions.js, app/assets/javascripts/react/components/Root.js, app/assets/javascripts/react/components/TouchMaps.js, app/assets/javascripts/react/components/presentational/Touch/Header.js, app/assets/javascripts/react/components/presentational/Touch/Maps.js, app/assets/javascripts/react/main.js, app/assets/javascripts/react/reducers/kioskReducer.js, app/controllers/kiosks_controller.rb, app/views/kiosk/show.html.erb, app/views/kiosks/_form.html.erb, app/views/kiosks/_kiosk.json.jbuilder, app/views/kiosks/index.html.erb, app/views/kiosks/show.html.erb, db/migrate/20180313180832_add_floor_number_to_kiosk.rb, db/schema.rb, package.json, spec/controllers/kiosks_controller_spec.rb, spec/views/kiosks/edit.html.erb_spec.rb, spec/views/kiosks/index.html.erb_spec.rb, spec/views/kiosks/new.html.erb_spec.rb, spec/views/kiosks/show.html.erb_spec.rb, yarn.lock
fixes #192  
Integrates LibNav functionality for associating a kiosk with any particular floor and having LibNav default to displaying that floor
=> adding floor number for each kiosk, providing this to the maps component

app/assets/javascripts/application.js, app/assets/javascripts/react/components/presentational/Touch/Header.js, app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js, app/assets/stylesheets/layouts/_main.scss, app/assets/stylesheets/layouts/_touch-kiosk.scss, app/views/layouts/react_application.html.erb, config/initializers/assets.rb, package.json, yarn.lock
=> adds primo search with a virtual keyboard for kiosk

app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js
updated keyboard layout per feedback by @dmoore
=> updates keyboard per feedback

Gemfile.lock
Update sprockets to fix security vulnerability
=> Updates sprockets to 3.7.2

app/assets/javascripts/react/components/presentational/Touch/HoursTable.js
Adds a description to the kiosks
=> Adds description if one exists

app/controllers/api/v1/hours_controller.rb, config/local_env.example.yml, spec/controllers/api/v1/hours_controller_spec.rb
=> env variables for api uri and route

lib/tasks/save_data.rake
create a backup of every slide record before deploying to production
=> add rake task to create a backup of current records

app/assets/javascripts/react/components/presentational/Interactive/Menu.js, app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js, app/assets/stylesheets/layouts/_interactive-kiosk.scss
=> added reset search button

Gemfile, Gemfile.lock, config/environments/development.rb, config/initializers/datadog-tracer.rb, config/initializers/lograge.rb, config/initializers/new_framework_defaults.rb
=> adds datadog and lograge for better logging and performance monitoring

Gemfile, Gemfile.lock
update to fix GitHub security alert
=> updated loofah to version greater than or equal to 2.2.3

Gemfile, Gemfile.lock
update to fix GitHub security alert
=> updated ffi gem

.circleci/config.yml, Gemfile.lock
update to address security alert
=> update rack gem

package.json, yarn.lock
updates `webpack-dev-server` to `">=3.1.11"` to address GitHub security update
=> update webpack-dev-server dependency

config/environments/development.rb
Allows for the webconsole to be used in development
=> allows web console on docker

app/views/collections/index.html.erb, app/views/kiosks/index.html.erb, app/views/slides/index.html.erb
=> update slide button locations

app/views/kiosk/show.json.jbuilder
=> caches kiosk slides for kiosk#show to last for 24 hours

app/assets/stylesheets/layouts/_donor-coverflow-kiosk.scss, app/javascript/react/components/presentational/DonorCoverflow/Kiosk.js, app/javascript/react/components/presentational/DonorCoverflow/LargeSlide.js
=> update layout and css to fit elements on screen

app/assets/stylesheets/layouts/_donor-coverflow-kiosk.scss, app/javascript/react/components/presentational/DonorCoverflow/Kiosk.js
fixes https://github.com/osulp/kiosks/issues/318
=> add bugfix for swipe left and right gestures in coverflow layout

app/javascript/react/components/presentational/DonorCoverflow/Kiosk.js
small tweaks to reduce the size of the cover-flow items to improve touch gestures
=> update coverflow settings

package.json, yarn.lock
update package.json to address security alerts
=> update for GitHub security alerts

README.md
Expand the Development Workflow section steps with commands used to get up and running. Some small formatting tweaks to existing content.
=> Expand Development Workflow section

app/views/kiosk/show.json.jbuilder
fixes similar issue https://github.com/osulp/kiosks/issues/336
=> add html_escape for collection detail

app/javascript/react/components/presentational/DonorCoverflow/Kiosk.js, app/javascript/react/components/presentational/DonorCoverflow/LargeSlide.js
=> add isRotating and currentIndex to rotate to the next slide

app/javascript/react/components/presentational/DonorCoverflow/LargeSlide.js
=> add decodeHtml to render detail (already encoded) in html/text format

app/javascript/react/components/presentational/Interactive/Header.js, app/javascript/react/components/presentational/Touch/Hours.js
=> update touch header and hours section layout

app/javascript/react/components/presentational/Circulation/Header.js, app/javascript/react/components/presentational/Interactive/Header.js, app/javascript/react/components/presentational/Touch/Header.js, app/javascript/react/components/presentational/Touch/HoursTable.js
This can be merged once https://github.com/osulp/API/pull/99 is merged and deployed
=> use formatted_hours_plain_text field

yarn.lock
fixes https://github.com/osulp/kiosks/issues/356
`yarn upgrade` to fix 1 serialize-javascript vulnerability
=> yarn upgrade 2-6-20

app/assets/stylesheets/layouts/_scarc-coverflow-kiosk.scss, app/javascript/react/components/presentational/ScarcCoverflow/GridSlide.js
=> adjust css for scarc grid view

app/javascript/react/components/presentational/ScarcCoverflow/Kiosk.js, app/javascript/react/components/presentational/ScarcCoverflow/MediaGrid.js
=> update scarc coverflow to use collection info instead of slide info

app/javascript/react/components/presentational/ScarcCoverflow/GridSlide.js
=> set layout after reloading items

app/assets/stylesheets/layouts/_scarc-coverflow-kiosk.scss, app/javascript/react/components/presentational/ScarcCoverflow/MediaModal.js, app/views/kiosk/show.json.jbuilder
=> add slide description in detail view (scarc layout)

app/uploaders/subtitle_uploader.rb
=> update store_dir to use uploaded base dir

app/views/directory/iframe_page.html
=> update to include iframe for staff directory

Gemfile, Gemfile.lock, app/controllers/directory_controller.rb, app/models/ckeditor/asset.rb, app/models/ckeditor/attachment_file.rb, app/models/ckeditor/picture.rb, app/models/directory.rb, app/uploaders/ckeditor_attachment_file_uploader.rb, app/uploaders/ckeditor_picture_uploader.rb, app/views/directory/editor_page.html.erb, app/views/directory/show.html.erb, config/initializers/assets.rb, config/initializers/ckeditor.rb, config/routes.rb, db/migrate/20200430141155_create_ckeditor_assets.rb, db/migrate/20200430162347_create_directories.rb, db/schema.rb, spec/factories/directories.rb, spec/models/directory_spec.rb
=> Add ckeditor and base structure for saving

app/assets/stylesheets/layouts/_admin-kiosk.scss, app/assets/stylesheets/main.scss, app/javascript/react/components/AdminKiosk.js, app/javascript/react/components/Root.js, app/javascript/react/components/presentational/Admin/Kiosk.js, app/javascript/react/components/presentational/Admin/Menu.js, app/javascript/react/components/presentational/shared/SlideGallery.js, lib/tasks/load_data.rake
=> Feature admin kiosk layout

app/controllers/directories_controller.rb, app/models/directory.rb, app/views/directories/index.html.erb, app/views/directories/new.html.erb, config/routes.rb
=> update directories to sort between osulp and ecampus

app/controllers/kiosk_controller.rb, app/javascript/react/components/presentational/Admin/Kiosk.js, app/javascript/react/components/presentational/Admin/MenuContent.js, app/views/kiosk/show.json.jbuilder
=> integrate directories content into MenuContent component

app/assets/stylesheets/layouts/_admin-kiosk.scss, app/javascript/react/components/presentational/Admin/MenuContent.js
This gets the looks and feel to a much better spot for the directories.
=> Make info into tables

app/assets/stylesheets/layouts/_admin-kiosk.scss, app/javascript/react/components/presentational/Admin/Menu.js
=> update to have buttons and aligning.

app/javascript/react/components/presentational/Admin/Kiosk.js
fixes https://github.com/osulp/kiosks/issues/408
reset main screen after 600,000 ms (10 min)
=> reset main screen after a period of inactivity

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/slides.js.coffee, app/assets/stylesheets/application.scss, app/assets/stylesheets/main.scss, app/views/slides/index.html.erb
=> install datatables and add to slides view

app/assets/stylesheets/layouts/_admin-kiosk.scss
=> updates the table and stops need for scrolling

app/assets/stylesheets/layouts/_admin-kiosk.scss
=> fits buttons on screen

app/assets/stylesheets/layouts/_admin-kiosk.scss, app/javascript/react/components/presentational/Admin/Menu.js
=> update buttons per designs

app/javascript/react/components/presentational/Admin/Kiosk.js
fixes #431 (checks off second item in the list)
=> update admin kiosk timeout to 45 seconds

app/assets/javascripts/application.js, app/assets/javascripts/moment.js, app/assets/javascripts/slides.js.coffee, app/views/layouts/application.html.erb, app/views/slides/index.html.erb
=> updates to use moment to automatically make dates sortable through datatables

.circleci/config.yml
Update CircleCI config to build and push containers to BCR
=> update kiosks CCI config to build/push containers

package.json, yarn.lock
=> Revert "update set-value"

app/assets/stylesheets/layouts/_interactive-kiosk.scss, app/javascript/react/components/presentational/shared/SlideGallery.js, app/uploaders/image_uploader.rb, app/views/kiosk/show.json.jbuilder
Add in the layout to fixed the consistence layout on the kiosk via the upload of image and video.
=> Fix the consistence layout

app/assets/stylesheets/layouts/_interactive-kiosk.scss, app/javascript/react/components/presentational/shared/SlideGallery.js, app/uploaders/image_uploader.rb
Testing the CircleCI see if it is running through
=> Test the resize and CircleCI

app/uploaders/image_uploader.rb
Changing the tag `resize_to_fit` to `resize_to_limit` and test it out to see if it works.
=> Refix with limit instead of fit to test out

app/assets/stylesheets/layouts/_interactive-kiosk.scss, app/uploaders/image_uploader.rb, spec/views/slides/index.html.erb_spec.rb, spec/views/slides/show.html.erb_spec.rb
Add in new resolution in the display to fix the image consistency.
=> Fix display setting

lib/tasks/kiosks/archive_slides.rake
Create a rake task to archive the slides we have on the kiosk for backup.
=> Archiving the Slides

app/assets/javascripts/application.js, app/assets/javascripts/navigation.js, app/views/slides/_active_slides_form.html.erb, app/views/slides/_all_slides_form.html.erb, app/views/slides/index.html.erb
Create a tab two setup one for active and one for all slides.
=> Setup the filter for slides
