osulp/kiosks

app/views/layouts/_ga.html.erb, app/views/layouts/application.html.erb, config/application_config.example.yml.erb
Fixes #5
Currently google analytics is looking at the url "http://test.library.oregonstate.edu" for testing purposes. Once we get closer to a live staging/production server we can swap the url over in google.
=> Adds google analytics and ga id to application config

app/assets/javascripts/react/actions/touchActions.js, app/assets/javascripts/react/components/TouchClassroomSchedule.js, app/assets/javascripts/react/components/TouchClassroomScheduleDay.js, app/assets/javascripts/react/components/presentational/Touch/ClassroomSchedule.js, app/assets/javascripts/react/components/presentational/Touch/ClassroomScheduleDay.js, app/assets/javascripts/react/components/presentational/Touch/Header.js, app/assets/javascripts/react/components/presentational/Touch/Hours.js, app/assets/javascripts/react/components/presentational/shared/ModalWindow.js, app/assets/javascripts/react/reducers/kioskReducer.js, app/assets/javascripts/react/reducers/touchReducer.js, app/assets/stylesheets/layouts/_touch-kiosk.scss, app/models/api/v1/classroom_calendar.rb, app/models/api/v1/classroom_event.rb, config/application_config.example.yml.erb, spec/javascripts/react/.factories.js, spec/javascripts/react/components/__snapshots__/DonorKiosk.test.js.snap, spec/javascripts/react/components/__snapshots__/DonorSlideGrid.test.js.snap, spec/javascripts/react/components/__snapshots__/Error.test.js.snap, spec/javascripts/react/components/__snapshots__/SlideGallery.test.js.snap, spec/javascripts/react/components/presentational/shared/ModalWindow.test.js, spec/javascripts/react/components/presentational/shared/__snapshots__/modalWindow.test.js.snap, spec/javascripts/react/reducers/__snapshots__/kioskReducer.test.js.snap, spec/javascripts/react/reducers/__snapshots__/touchReducer.test.js.snap, spec/javascripts/react/reducers/touchReducer.test.js, spec/models/api/v1/classroom_calendar_spec.rb, spec/models/api/v1/classroom_event_spec.rb
Touch kiosk UI for interacting with classroom schedule api backend.. 
TODO: 
- Translate each event row into a horizontally aligned bar with color coding per room to indicate what time segments are reserved for that event.
- Organize the UI so that the day events calendar is at the top of the view, and the bottom of the view is split into a filter grid and calendar side-by-side 
```
|--------------------------------------------------|
Full Day Event Calendar                           
|--------------------------------------------------|
Room Filter Grid        |     Calendar Picker   
|--------------------------------------------------|
```
=> add basic UI for classroom schedule

app/assets/javascripts/react/components/TouchClassroomSchedule.js, app/assets/javascripts/react/components/presentational/Touch/ClassroomSchedule.js
fixes classroom schedule in production, which has JS aggressively pruned by webpack causing the property to be missing in this circumstance
=> classroom schedule production bugfix

app/assets/javascripts/react/components/presentational/Circulation/Header.js, app/assets/javascripts/react/components/presentational/Touch/ClassroomScheduleDay.js, app/assets/javascripts/react/components/presentational/Touch/Header.js, app/assets/javascripts/react/components/presentational/Touch/Hours.js, app/assets/javascripts/react/components/presentational/Touch/HoursTable.js, spec/controllers/collections_controller_spec.rb, spec/views/date_ranges/index.html.erb_spec.rb
fixes #114 
- Updated the hours table and the kiosk headers (touch, and circulation) so that they display the formatted hours instead of the raw open/close values, see screenshot bellow
Touch kiosk header
Circulation header
- Updated Hours.js so that when the hours popup is closed, the headers will show today's hours instead of the previously selected hours in the calendar
- Screenshot for new hours popup
- Removed the contact column from the classroom schedule windows as requested by Circulation
=> updated kiosk to use formatted hours instead of open/close values

config/deploy.rb, spec/models/api/v1/classroom_calendar_spec.rb, spec/models/api/v1/classroom_event_spec.rb
- updated Capistrano version to 3.8.0
- fixed calendar specs to take into account different set of time offsets
=> updated calendar specs and cap deploy version

app/assets/javascripts/react/components/presentational/Touch/Hours.js, app/assets/stylesheets/layouts/_touch-kiosk.scss
- used intervals instead of timeouts in the hours component in the hours window
- updated the css so that the bullets used to switch slides would show the proper contrast depending on the background:
=> updated hours window and bullet slide css

app/controllers/api/v1/rooms_controller.rb
fixes #143 
Somehow using Rails time zone parsing and translating on the same line of code causes an intermittent bug to make an invalid SQL query using PST times.
=> fixes a bug dealing with time zone parsing and translating

app/assets/javascripts/react/components/TouchSearchPrimo.js, app/assets/javascripts/react/components/presentational/Touch/Header.js, app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js
fixes #136 
added `1Search` button and an iframe component to render primo search UI in a touch kiosk component
=> integrate primo search in touch kiosk

app/assets/javascripts/react/components/presentational/Circulation/Kiosk.js, app/assets/javascripts/react/components/presentational/Donor/Kiosk.js, app/assets/javascripts/react/components/presentational/Touch/Kiosk.js, app/controllers/kiosk_controller.rb, app/models/kiosk.rb, app/views/kiosks/index.html.erb, spec/models/kiosk_spec.rb
fixes #176 
After discussing issue #176 with @revgum Josh had the idea of enhancing feature https://github.com/osulp/kiosks/pull/173 by setting a grace period (1 min) in order to allow any client to restart itself during this timeframe. See diagram below:
- This PR implements the grace period (1 minute past restart_at) in `reload_kiosk?`
- This update also adds a 1-minute delay to fetch `restart_kiosk` when the kiosk is mounted on start. This change allows the grace period to get closed first before sending the next request to fetch `restart_kiosk`
=> updated reload_kiosk method to allow a grace period for all clients

Gemfile, Gemfile.lock, app/controllers/api/v1/hours_controller.rb, spec/controllers/api/v1/hours_controller_spec.rb
So this looks like its working quite nicely, but its only requesting for the day of. I still have to see what kind of request is coming in with {"dates":["2016-01-01","2016-01-02","2016-01-03"]} in the body of the request. Its not working all the way for multiple dates, but single date is working great.
=> replace drupal hours call with api call

db/migrate/20161208192704_add_attachment_image_to_slides.rb, db/migrate/20170327215219_paperclip_to_carrierwave.rb
commenting out migration actions related to paperclip since it was removed in https://github.com/osulp/kiosks/pull/167
paperclip was replaced with carrierwave in https://github.com/osulp/kiosks/pull/122
=> updated migrate errors to ignore migrations related to paperclip

Gemfile, Gemfile.lock
fixes:
```
Puma starting in single mode...
* Version 3.8.2 (ruby 2.5.1-p57), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: staging
! Unable to load application: Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
```
=> updated mysql2 in Gemfile

app/assets/javascripts/react/components/presentational/Circulation/Kiosk.js
Disabling the counter for now until we have a workaround for issue: https://github.com/osulp/kiosks/issues/259
=> disable room counter for circulation kiosk display

app/assets/javascripts/react/components/presentational/shared/SlideGallery.js, app/views/kiosk/show.json.jbuilder
This lets a slide know what kiosk it is currently being rendered on. This can ensure that the slide can be rendered in a specific size depending on its current kiosk. This allows for shared collections over multiple kiosks to work with the possibility that the kiosks might have different rendering expectations.
=> Makes slide know what kiosk its being rendered on.

package.json, yarn.lock
Update jquery to fix security alert CVE-2019-11358
=> update jquery to 3.4.0 or greater

package.json, yarn.lock
Upgrade fstream to version 1.0.12 or later.
`yarn upgrade fstream@^1.0.12` to address security alert WS-2019-0100
=> upgrade fstream package to address security alert

app/javascript/react/components/presentational/DonorCoverflow/Kiosk.js, app/javascript/react/components/presentational/DonorCoverflow/LargeSlide.js, app/views/kiosk/show.json.jbuilder
Coverflow updates:
- update cover-flow layout to use a large derivative [resize_to_limit: [600, 600]](https://github.com/osulp/kiosks/blob/master/app/uploaders/image_uploader.rb#L49-L51) of images instead of the original size
- update zoom in/out timeout to 30 seconds (instead of 5) when clicking images in the detail page
=> updates for cover-flow layout

app/models/collection.rb, app/models/kiosk.rb, app/models/kiosk_slide.rb, app/models/slide.rb
fixes https://github.com/osulp/kiosks/issues/310
related https://github.com/osulp/kiosks/issues/299#issuecomment-472488686
- Since we have a cache for 24 hours in each kiosk display at https://github.com/osulp/kiosks/blob/master/app/views/kiosk/show.json.jbuilder#L3 whenever we tried to add new slides, the update wouldn't take effect until the next day, causing a delay for displaying updated slides
- This updates the kiosk-slide models so that they get refreshed for the cache when adding/updating/deleting slides
=> add touch method to slides model for cache refresh

app/javascript/react/components/presentational/DonorCoverflow/LargeSlide.js
fixes https://github.com/osulp/kiosks/issues/324
update `clearTimeout` to use `hide_timeout` instead of `hideTimeout`, and similarly with `exiting_timeout`.
=> Fix large slide timeout

app/javascript/react/components/presentational/DonorCoverflow/LargeSlide.js
fixes #327 
This updates app/javascript/react/components/presentational/DonorCoverflow/LargeSlide.js and adds a timeout for rotating slides in the DonorCoverlow layout
=> Set rotating timeout to 30 seconds

app/javascript/react/components/presentational/Circulation/Rooms.js
I did everything I possibly could muster up trying to fix this thing, but for some reason webpack isnt compiling the files proper and its failing to set the global FlipClock variable. So this file cannot find it. This was inaccurate as well though, so maybe disabling it until we find a better solution is the right way to go.
=> removes broken flipclock

app/views/kiosk/show.json.jbuilder, spec/views/kiosks/show.json.jbuilder_spec.rb
Fixes #336 
(in my testing it was the just the ' regular apostrophe causing problems, not the curly one also mentioned in 336)
This will also handle newlines correctly, like in Caption since it's a multi-line input field. I couldn't find a way to make the spec output match exactly for that one. But from my local testing the JSON output with newlines is: `"caption":"test caption for slide 3\r\nline 2\r\nline 3\r\nline 4",`
=> Escape title and caption in kiosk/slide JSON output. Add spec.

app/javascript/react/components/presentational/Interactive/Header.js, app/javascript/react/components/presentational/Touch/HoursTable.js
A `<br>` tag was added to `formatted_hours` in https://github.com/osulp/API/pull/89 to improve readability in the library website.
This PR fixes an issue when rendering raw html coming from the hours API. The update basically replaces the `<br>` with `, ` to render the hours in one line in the `Header` and `HoursTable` components for now. 
I think we should introduce a non-html field in https://github.com/osulp/API that can be used in the kiosks. Another option would be to add logic in the react js components to sanitize and decode html tags coming from the hours API.
current behavior:
expected behavior:
=> replace html br tag with comma

app/javascript/react/components/presentational/ScarcCoverflow/GridSlide.js, app/javascript/react/components/presentational/ScarcCoverflow/MediaGrid.js
fixes #376 
Additional update: use masonry `reloadItems` instead of `destroy`
=> setupGrid on selected coverflow index

app/controllers/application_controller.rb, config.ru, config/initializers/honeycomb.rb
@DeadCatLady @decimalator Im only a honeycomb noob, so im not even sure if this was the thing, but I guess `Honeycomb.init` didnt exist anymore, so when firing up our server locally, we would run into some issues.
Removing the Honeycomb.init would allow the app to proceed but hit another snag in the application controller.
Im assuming since Honeycomb wasnt being initialized, the instance variable wasnt being loaded into the app, so `Honeycomb` model was returning a nil value. 
So in order to get Honeycomb initialized proper in the app, I generated an initializer per their documentation. This allowed the add_field method to work as expected, except it takes 2 variables now instead of 3. So I updated that too. Its working locally now, so I wanted to have you two take a look at this so we …
=> adds initializer and updates the add_field
